### ISSUE TITLE
pygame не воспроизводит фоновую музыку, так как не понимает mp3

### ISSUE THREAD

**Issue by ilya-nikolaev** [whoamins/Dino#4]
Нужно конвертировать музыку в проекте в другой формат, возможно это проблема совместимости

**Comment by whoamins** [comment]
Привет! Если склонировать код из master ветки, то звуки работают хорошо, пробую разобраться почему не работает у других. В любом случае дам фидбек!

**Comment by ilya-nikolaev** [comment]
> Привет! Если склонировать код из master ветки, то звуки работают хорошо, пробую разобраться, почему не работает у других. В любом случае дам фидбек!

Возможно дело в том что у меня Linux Mint

**Comment by ilya-nikolaev** [comment]
Да, pygame поддерживает mp3, но не в Ubuntu)
